IPTUPLA = 0
PUERTOTUPLA = 1

TIPODEPROTOCOLO = "SW" 

# Estos dos estan en bytes
TAMANOHEADER = 4
TAMANOPAQUETE = 504

TAMANOLECTURAARCHIVO = None

TIMEOUT = 5.0

FORMATORED = "!I"
FORMATONATIVO = "=I"

MENSAJECONECCION = b"SYN"
# ESTOS TIENEN QUE TENER EL MISMO TAMANO... bueno en realidad no.
# pero hace las cosas ms faciles. 
MENSAJEUPLOAD = b"UPL"
MENSAJEDOWNLOAD = b"DOW"

MENSAJEACEPTARCONECCION= b"SYNACK"
